create extension if not exists pgcrypto;

create schema if not exists public;

do $$
begin
  create type public.os_family as enum (
    'ios',
    'android',
    'windows',
    'macos',
    'linux',
    'unknown'
  );
exception
  when duplicate_object then null;
end;
$$;

do $$
begin
  create type public.membership_role as enum (
    'owner',
    'admin',
    'moderator'
  );
exception
  when duplicate_object then null;
end;
$$;

do $$
begin
  create type public.membership_status as enum (
    'invited',
    'active',
    'disabled'
  );
exception
  when duplicate_object then null;
end;
$$;

do $$
begin
  create type public.session_status as enum (
    'draft',
    'active',
    'completed'
  );
exception
  when duplicate_object then null;
end;
$$;

do $$
begin
  create type public.age_mode as enum (
    'fixed',
    'variable'
  );
exception
  when duplicate_object then null;
end;
$$;

drop trigger if exists flowa_profiles_set_updated_at on public.profiles;
drop trigger if exists flowa_memberships_set_updated_at on public.memberships;
drop trigger if exists flowa_sessions_set_updated_at on public.sessions;
drop trigger if exists flowa_organizations_set_updated_at on public.organizations;

drop view if exists public.session_overview cascade;
drop view if exists public.session_age_statistics cascade;
drop view if exists public.latest_session_participants cascade;

drop table if exists public.session_collaborators cascade;
drop table if exists public.memberships cascade;
drop table if exists public.profiles cascade;
drop table if exists public.organizations cascade;

create table if not exists public.sessions (
  id uuid primary key default gen_random_uuid(),
  organization_id text not null,
  slug text not null unique,
  name text not null,
  description text not null default '',
  screen_time_limit_minutes integer not null default 60 check (screen_time_limit_minutes between 1 and 1440),
  age_mode public.age_mode not null default 'variable',
  fixed_age integer,
  age_recommendations_enabled boolean not null default true,
  age_recommendations jsonb not null default '[]'::jsonb,
  status public.session_status not null default 'active',
  created_by text not null,
  starts_at timestamptz not null default timezone('utc', now()),
  ends_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint public_sessions_fixed_age_check check (
    (age_mode = 'fixed' and fixed_age between 1 and 120)
    or (age_mode = 'variable' and fixed_age is null)
  )
);

create table if not exists public.session_submissions (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.sessions (id) on delete cascade,
  participant_key uuid not null,
  age integer not null check (age between 1 and 120),
  screen_time_minutes integer not null check (screen_time_minutes between 0 and 1440),
  detected_os public.os_family not null default 'unknown',
  ip_address inet,
  entered_at timestamptz,
  client_metadata jsonb not null default '{}'::jsonb,
  user_agent text,
  submitted_at timestamptz not null default timezone('utc', now()),
  entry_date date not null default (timezone('utc', now())::date)
);

alter table if exists public.session_submissions
  add column if not exists entered_at timestamptz;

alter table if exists public.session_submissions
  add column if not exists client_metadata jsonb not null default '{}'::jsonb;

create table if not exists public.activity_log (
  id bigint generated by default as identity primary key,
  organization_id text not null,
  session_id uuid references public.sessions (id) on delete set null,
  actor_user_id text,
  activity_type text not null,
  title text not null,
  description text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

alter table if exists public.sessions
  alter column organization_id type text using organization_id::text;

alter table if exists public.sessions
  alter column created_by type text using created_by::text;

alter table if exists public.activity_log
  alter column organization_id type text using organization_id::text;

alter table if exists public.activity_log
  alter column actor_user_id type text using actor_user_id::text;

create index if not exists public_sessions_org_idx
  on public.sessions (organization_id, created_at desc);

create index if not exists public_sessions_status_idx
  on public.sessions (status, starts_at desc);

create index if not exists public_session_submissions_session_idx
  on public.session_submissions (session_id, submitted_at desc);

create index if not exists public_session_submissions_participant_idx
  on public.session_submissions (session_id, participant_key, submitted_at desc);

create index if not exists public_session_submissions_entry_date_idx
  on public.session_submissions (entry_date desc);

create index if not exists public_session_submissions_os_idx
  on public.session_submissions (detected_os, submitted_at desc);

create index if not exists public_activity_log_org_idx
  on public.activity_log (organization_id, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists public_sessions_set_updated_at on public.sessions;
create trigger public_sessions_set_updated_at
before update on public.sessions
for each row
execute function public.set_updated_at();

create or replace view public.latest_session_participants as
select distinct on (session_id, participant_key)
  id,
  session_id,
  participant_key,
  age,
  screen_time_minutes,
  detected_os,
  ip_address,
  entered_at,
  client_metadata,
  user_agent,
  submitted_at,
  entry_date
from public.session_submissions
order by session_id, participant_key, submitted_at desc;

create or replace view public.session_age_statistics as
select
  session_id,
  case
    when age < 25 then '18-24'
    when age < 35 then '25-34'
    when age < 45 then '35-44'
    when age < 55 then '45-54'
    else '55+'
  end as age_bucket,
  count(*)::integer as participants,
  round(avg(screen_time_minutes)::numeric, 1) as average_minutes,
  max(screen_time_minutes)::integer as maximum_minutes
from public.latest_session_participants
group by session_id, 2;

create or replace view public.session_overview as
select
  sessions.id as session_id,
  sessions.organization_id,
  sessions.slug,
  sessions.name,
  sessions.status,
  sessions.screen_time_limit_minutes,
  sessions.created_at,
  sessions.starts_at,
  sessions.ends_at,
  count(participants.id)::integer as participant_count,
  round(avg(participants.screen_time_minutes)::numeric, 1) as average_minutes,
  max(participants.screen_time_minutes)::integer as maximum_minutes,
  max(participants.submitted_at) as latest_submission_at
from public.sessions as sessions
left join public.latest_session_participants as participants
  on participants.session_id = sessions.id
group by
  sessions.id,
  sessions.organization_id,
  sessions.slug,
  sessions.name,
  sessions.status,
  sessions.screen_time_limit_minutes,
  sessions.created_at,
  sessions.starts_at,
  sessions.ends_at;
